version: '3.8'

services:
  # Servicio principal del chatbot
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-erp-chatbot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./whatsapp-session:/usr/src/app/whatsapp-session
      - ./logs:/usr/src/app/logs
    network_mode: "host"
networks:
  default:
    driver: bridge